"""Add raw_data field to articles

Revision ID: 317ff996d653
Revises: c125edf72614
Create Date: 2025-06-25 11:14:10.519318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '317ff996d653'
down_revision: Union[str, Sequence[str], None] = 'c125edf72614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('raw_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'raw_data')
    # ### end Alembic commands ###
