"""add_fields_to_sentiment_model

Revision ID: 365f9618af08
Revises: 317ff996d653
Create Date: 2025-06-25 15:22:59.023227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365f9618af08'
down_revision: Union[str, Sequence[str], None] = '317ff996d653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentiments', sa.Column('label', sa.String(), nullable=True))
    op.add_column('sentiments', sa.Column('subjectivity', sa.Float(), nullable=True))
    op.add_column('sentiments', sa.Column('raw_data', sa.JSON(), nullable=True))
    op.add_column('sentiments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentiments', 'updated_at')
    op.drop_column('sentiments', 'raw_data')
    op.drop_column('sentiments', 'subjectivity')
    op.drop_column('sentiments', 'label')
    # ### end Alembic commands ###
