"""add_narrative_discovery_fields_to_articles

Revision ID: a1555ddf25dc
Revises: 6e48650eed26
Create Date: 2025-10-11 16:11:31.405109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1555ddf25dc'
down_revision: Union[str, Sequence[str], None] = '6e48650eed26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
