"""Add description field to articles

Revision ID: b06092437ed2
Revises: 72a1279d7a31
Create Date: 2025-06-25 11:07:26.791927

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b06092437ed2"
down_revision: Union[str, Sequence[str], None] = "72a1279d7a31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("articles", sa.Column("description", sa.String(), nullable=True))
    op.alter_column(
        "sources",
        "id",
        existing_type=sa.VARCHAR(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sources",
        "id",
        existing_type=sa.VARCHAR(),
        server_default=sa.text("nextval('sources_id_seq'::regclass)"),
        existing_nullable=False,
    )
    op.drop_column("articles", "description")
    # ### end Alembic commands ###
