"""Add url_to_image field to articles

Revision ID: c125edf72614
Revises: ddd1d84e4130
Create Date: 2025-06-25 11:12:01.171667

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c125edf72614"
down_revision: Union[str, Sequence[str], None] = "ddd1d84e4130"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("articles", sa.Column("url_to_image", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("articles", "url_to_image")
    # ### end Alembic commands ###
