"""Ensure all models including User and Alert are in schema

Revision ID: c6a4d605f8da
Revises: ec1408942a0d
Create Date: 2025-07-11 16:47:14.238020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a4d605f8da'
down_revision: Union[str, Sequence[str], None] = 'ec1408942a0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
